spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking-liquibase
    username: root
    password: root

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.springframework.security: DEBUG